### ISSUE TITLE
Error with bower and wiredep install 

### ISSUE THREAD

**Issue by vqoph** [andydennis/angularjs-scorm-wrapper#2]
```
Starting 'wiredep'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: must provide pattern
    at new GlobSync (/(...)/node_modules/glob/sync.js:31:11)
    at Function.globSync [as sync] (/(...)/node_modules/glob/sync.js:26:10)
    at /(...)/node_modules/wiredep/lib/detect-dependencies.js:113:14
    at Array.reduce (native)
    at findMainFiles (/(...)/node_modules/wiredep/lib/detect-dependencies.js:111:29)
    at /(...)/node_modules/wiredep/lib/detect-dependencies.js:165:17
    at /(...)/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/(...)/node_modules/lodash/lodash.js:3001:24)
    at /(...)/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/(...)/node_modules/lodash/lodash.js:9359:14)
    at detectDependencies (/(...)/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/(...)/node_modules/wiredep/wiredep.js:70:39)
    at DestroyableTransform._transform (/(...)/node_modules/wiredep/wiredep.js:136:34)
    at DestroyableTransform.Transform._read (/(...)/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/(...)/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/(...)/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/(...)/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at DestroyableTransform.Writable.write (/(...)/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at write (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/(...)/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/(...)/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /(...)/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```

possible issues in bower.json file :
```
{
  "name": "AngularJS SCORM Wrapper", <=  should use dash-case and no whitespace
  "version": "1.2.1",
  "main": "", <=no main file (should specify "dist/angularjs-scorm-wrapper.min.js")
  "ignore": [
    ".jshintrc",
    "**/*.txt"
  ],
  "dependencies": {
  },
  "devDependencies": {
  }
}
```

see https://github.com/bower/spec/blob/master/json.md#name

**Comment by adennis-modus** [comment]
Can you confirm this is now fixed and close the issue?

Thanks

**Comment by rpigu-i** [comment]
Closed.
